# Controller Manager Parameters
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    # === RENAMED THE CONTROLLER ===
    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

# === RENAMED THE CONTROLLER PARAMETERS ===
joint_trajectory_controller:
  ros__parameters:
    # === UPDATED JOINT LIST ===
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
    
    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

    allow_partial_joints_goal: true
    # open_loop_control: true # Use this if your robot doesn't have state feedback
    
    # === UPDATED GAINS ===
    gains:
      joint1: {p: 100.0, i: 0.1, d: 10.0}
      joint2: {p: 100.0, i: 0.1, d: 10.0}
      joint3: {p: 100.0, i: 0.1, d: 10.0}
      joint4: {p: 100.0, i: 0.1, d: 10.0}
      joint5: {p: 100.0, i: 0.1, d: 10.0}
      joint6: {p: 100.0, i: 0.1, d: 10.0}
