"""Phase 2 — Auto URDF / SRDF generation from robot profile (PLAN.md §8)."""

from __future__ import annotations

import textwrap
from pathlib import Path
from typing import Any

import yaml

from ..bridge_constants import get_config_dir


class UrdfGenerator:
    """Generate robot description files from YAML profile + DH parameters."""

    AGENT_ID = "urdf_generator_agent"

    def __init__(self, logger=None):
        self._logger = logger
        self.output_dir = Path(get_config_dir()) / "generated"
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def generate_from_profile(
        self,
        profile_path: Path,
        kinematic_path: Path | None = None,
    ) -> dict[str, Any]:
        profile = yaml.safe_load(profile_path.read_text(encoding="utf-8")) or {}
        robot = profile.get("robot", profile)
        name = robot.get("name", "visiona_robot").replace(" ", "_").lower()
        dof = robot.get("dof", 6)
        dh_rows = self._load_dh(kinematic_path)

        urdf_path = self.output_dir / f"{name}.urdf.xacro"
        srdf_path = self.output_dir / f"{name}.srdf"
        manifest_path = self.output_dir / f"{name}_manifest.yaml"

        urdf_content = self._build_urdf_xacro(name, dof, dh_rows, profile)
        srdf_content = self._build_srdf(name, dof)

        urdf_path.write_text(urdf_content, encoding="utf-8")
        srdf_path.write_text(srdf_content, encoding="utf-8")

        manifest = {
            "robot_name": name,
            "dof": dof,
            "urdf_path": str(urdf_path),
            "srdf_path": str(srdf_path),
            "source_profile": str(profile_path),
            "confidence": 0.88 if dh_rows else 0.65,
        }
        manifest_path.write_text(yaml.safe_dump(manifest, sort_keys=False), encoding="utf-8")

        if self._logger:
            self._logger.info(f"Generated URDF ? {urdf_path}")

        return manifest

    def _load_dh(self, kinematic_path: Path | None) -> list[list[float]]:
        if not kinematic_path or not kinematic_path.is_file():
            return []
        raw = yaml.safe_load(kinematic_path.read_text(encoding="utf-8")) or {}
        params = raw.get("kinematic_params", {}).get("ros__parameters", raw)
        dh = params.get("dh_params", {})
        rows = []
        for key in ("joint_0", "joint_1", "joint_2", "joint_3"):
            j = dh.get(key, {})
            rows.append([
                float(j.get("a", 0.0)),
                float(j.get("alpha", 0.0)),
                float(j.get("d", 0.0)),
                float(j.get("theta_offset", 0.0)),
            ])
        return rows

    def _build_urdf_xacro(self, name: str, dof: int, dh_rows: list, profile: dict) -> str:
        hw = profile.get("hardware", profile.get("kinematic_hardware", {}))
        home = hw.get("home_position", [90.0] * min(dof, 6))

        link_blocks = []
        joint_blocks = []
        link_names = ["base", "base_link", "link_1_shoulder", "link_2_elbow", "link_3_wrist", "gripper_base"]

        for i, lname in enumerate(link_names[: min(len(link_names), dof + 1)]):
            length = dh_rows[i][0] if i < len(dh_rows) else 0.1
            link_blocks.append(textwrap.dedent(f"""
                <link name="{lname}">
                  <visual><geometry><box size="{max(length, 0.05):.3f} 0.04 0.04"/></geometry></visual>
                  <collision><geometry><box size="{max(length, 0.05):.3f} 0.04 0.04"/></geometry></collision>
                </link>""").strip())

        parent = "base"
        for i in range(min(dof, 5)):
            child = link_names[i + 1] if i + 1 < len(link_names) else f"link_{i}"
            d_val = dh_rows[i][2] if i < len(dh_rows) else 0.0
            joint_blocks.append(textwrap.dedent(f"""
                <joint name="joint_{i}" type="revolute">
                  <parent link="{parent}"/>
                  <child link="{child}"/>
                  <origin xyz="0 0 {d_val:.3f}" rpy="0 0 0"/>
                  <axis xyz="0 0 1"/>
                  <limit lower="-3.14" upper="3.14" effort="10" velocity="1.0"/>
                </joint>""").strip())
            parent = child

        return textwrap.dedent(f"""\
            <?xml version="1.0"?>
            <!-- AUTO-GENERATED by URAF UrdfGenerator — {name} -->
            <robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="{name}">
              <link name="world"/>
              <joint name="world_to_base" type="fixed">
                <parent link="world"/><child link="base"/>
                <origin xyz="0 0 0" rpy="0 0 0"/>
              </joint>
              {chr(10).join(link_blocks)}
              {chr(10).join(joint_blocks)}
              <!-- Home reference (deg): {home} -->
            </robot>""")

    def _build_srdf(self, name: str, dof: int) -> str:
        joints = [
            "base_link_joint", "link_1_shoulder_joint", "link_2_elbow_joint",
            "link_3_wrist_joint", "link_3_wrist_to_gripper_base_joint",
        ][: min(dof, 5)]
        joint_xml = "\n        ".join(f'<joint name="{j}" value="1.57"/>' for j in joints)
        group_joints = "\n        ".join(f'<joint name="{j}"/>' for j in joints)
        return textwrap.dedent(f"""\
            <?xml version="1.0" encoding="UTF-8"?>
            <robot name="{name}">
              <group name="arm">
                {group_joints}
              </group>
              <group_state name="home" group="arm">
                {joint_xml}
              </group_state>
              <virtual_joint name="virtual_joint" type="fixed" parent_frame="world" child_link="base"/>
            </robot>""")
