# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - joint_trajectory_controller

  joint_trajectory_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - base_link_joint
      - link_1_shoulder_joint
      - link_2_elbow_joint
      - link_3_wrist_joint
      - link_3_wrist_to_gripper_base_joint
      - gripper