# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    Gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:
  ros__parameters:
    joints:
      - base_link_joint
      - link_1_shoulder_joint
      - link_2_elbow_joint
      - link_3_wrist_joint
      - link_3_wrist_to_gripper_base_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
Gripper_controller:
  ros__parameters:
    joints:
      - gripper
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity