[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps =
    adafruit/Adafruit PWM Servo Driver Library
    adafruit/Adafruit INA219
    ; FastLED/FastLED
monitor_speed = 921600 

; custom_microros_distro = foxy
; extra_scripts = pre:microros_build.py
; custom_microros_distro = foxy
; extra_scripts = pre:microros_build.py