# Controller Manager Parameters
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

# Controller Parameters
joint_trajectory_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
    
    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

    allow_partial_joints_goal: true
    
    # =================================================================
    # === THE FIX: Reduced gains for a stable physics engine ===
    # =================================================================
    gains:
      joint1: {p: 100.0, i: 0.1, d: 10.0}
      joint2: {p: 100.0, i: 0.1, d: 10.0}
      joint3: {p: 100.0, i: 0.1, d: 10.0}
      joint4: {p: 50.0,  i: 0.1, d: 5.0}
      joint5: {p: 50.0,  i: 0.1, d: 5.0}
